services:
  db:
    image: postgres:17
    container_name: e-patrol-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: epatrol
      POSTGRES_PASSWORD: epatrol_dev
      POSTGRES_DB: epatrol

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
